=== loiclacombe/clean-emulator-frontend/SystemsData/emuconfig.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="emuconfig"
    targetNamespace="http://loiclacombe.com/emuconfig.xsd"
    elementFormDefault="qualified"
    xmlns="http://loiclacombe.com/emuconfig.xsd"
    xmlns:tns="http://loiclacombe.com/emuconfig.xsd"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
>
  <xs:complexType name="EmulatedSystem">
    <xs:sequence>
      <xs:element name="CompatibleEmulator" type="tns:CompatibleEmulator" minOccurs="1" maxOccurs="1"/>
    </xs:sequence>
    <xs:attribute name="Description" type="xs:string" />
    <xs:attribute name="ShortName" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="CompatibleEmulator">
    <xs:attribute name="Name" type="xs:string" />
    <xs:attribute name="LibraryName" type="xs:string" />
    <xs:attribute name="Enabled" type="xs:boolean" default="true" />
  </xs:complexType>
  <xs:complexType name="Library">
    <xs:attribute name="Name" type="xs:string" />
    <xs:attribute name="LibraryClass" type="xs:string" />
    <xs:attribute name="LibraryFolderKey" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="Emulator">
    <xs:sequence>
      <xs:element name="EmulatorPathKey" type="xs:string" />
      <xs:element name="CliParameters" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="Name" type="xs:string" />
    <xs:attribute name="Description" type="xs:string" />
  </xs:complexType>
  <xs:complexType name="SystemGroup">
    <xs:sequence>
      <xs:element name="EmulatedSystem" type="tns:EmulatedSystem" minOccurs="1" maxOccurs="unbounded"/>
    </xs:sequence>
    <xs:attribute name="Description" type="xs:string" />
    <xs:attribute name="Enabled" type="xs:boolean" default="true"  />
  </xs:complexType>
  
  <xs:element name="SystemConfigRoot">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="SystemGroup" type="tns:SystemGroup" minOccurs="1" maxOccurs="unbounded" />
        <xs:element name="Emulator" type="tns:Emulator" minOccurs="1" maxOccurs="unbounded" />
        <xs:element name="Library" type="tns:Library" minOccurs="1" maxOccurs="unbounded" />
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== loiclacombe/clean-emulator-frontend/SetData/emuconfig.xml
<?xml version="1.0" encoding="utf-8" ?>
<SystemConfigRoot xmlns="http://loiclacombe.com/emuconfig.xsd"
   xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance"
   xsi:schemaLocation="http://loiclacombe.com/emuconfig.xsd file:emuconfig.xsd">
  <SystemGroup Description="Consoles" >
    <EmulatedSystem Description="Famicom">
      <CompatibleEmulator
        Name="nestopia"
        LibraryClass="Parsers.SplitSet.Library"
        RomFolderKey="higan.famicom.library"/>
    </EmulatedSystem>

    <EmulatedSystem Description="Game Boy">
      <CompatibleEmulator
        Name="gambatte"
        LibraryClass="Parsers.SplitSet.Library"
        RomFolderKey="gambatte.gb.library"/>
    </EmulatedSystem>
    <EmulatedSystem Description="Game Boy Color">
      <CompatibleEmulator
        Name="gambatte"
        LibraryClass="Parsers.SplitSet.Library"
        RomFolderKey="gambatte.gbc.library"/>
    </EmulatedSystem>
    <EmulatedSystem Description="Game Boy Avance">
      <CompatibleEmulator
        Name="mednafen"
        LibraryClass="Parsers.SplitSet.Library"
        RomFolderKey="mednafen.gba.library"/>
    </EmulatedSystem>
    <EmulatedSystem Description="Game Gear">
      <CompatibleEmulator
        Name="fusion"
        LibraryClass="Parsers.SplitSet.Library"
        RomFolderKey="fusion.gamegear.library"/>
    </EmulatedSystem>
    <EmulatedSystem Description="Master System">
      <CompatibleEmulator
        Name="fusion"
        LibraryClass="Parsers.SplitSet.Library"
        RomFolderKey="fusion.mastersystem.library"/>
    </EmulatedSystem>
    <EmulatedSystem Description="Megadrive">
      <CompatibleEmulator 
        Name="fusion"
        LibraryClass="Parsers.SplitSet.Library"
        RomFolderKey="fusion.megadrive.library"/>
    </EmulatedSystem>
    <EmulatedSystem Description="Nintendo 64">
      <CompatibleEmulator
        Name="project64"
        LibraryClass="Parsers.SplitSet.Library"
        RomFolderKey="project64.nintendo64.library"/>
    </EmulatedSystem>
    <EmulatedSystem Description="Super Famicom">
      <CompatibleEmulator
        Name="higan"
        LibraryClass="Parsers.Higan.Library"
        RomFolderKey="higan.superfamicom.library"/>
    </EmulatedSystem>
    
  </SystemGroup>
  <Emulator Name="higan" Description="Higan">
    <EmulatorPathKey>emulators.higan.path</EmulatorPathKey>
    <CliParameters>"{0}" -fullscreen</CliParameters>
  </Emulator>
  <Emulator Name="fusion" Description="Fusion">
    <EmulatorPathKey>emulators.fusion.path</EmulatorPathKey>
    <CliParameters>"{0}" -fullscreen</CliParameters>
  </Emulator>
  <Emulator Name="nestopia" Description="NestopiaUE">
    <EmulatorPathKey>emulators.nestopia.path</EmulatorPathKey>
    <CliParameters>"{0}" -fullscreen</CliParameters>
  </Emulator>
  <Emulator Name="gambatte" Description="NestopiaUE">
    <EmulatorPathKey>emulators.gambatte.path</EmulatorPathKey>
    <CliParameters>"{0}" -fullscreen"</CliParameters>
  </Emulator>
  <Emulator Name="mednafen" Description="Mednafen">
    <EmulatorPathKey>emulators.mednafen.path</EmulatorPathKey>
    <CliParameters>"{0}"</CliParameters>
  </Emulator>
  <Emulator Name="project64" Description="Project 64">
    <EmulatorPathKey>emulators.project64.path</EmulatorPathKey>
    <CliParameters>"{0}" -fullscreen</CliParameters>
  </Emulator>
</SystemConfigRoot>

=== loiclacombe/clean-emulator-frontend/SystemsData/emuconfig.xml
<?xml version="1.0" encoding="utf-8"?>

<SystemConfigRoot xmlns="http://loiclacombe.com/emuconfig.xsd"
                  xmlns:xsi="http://www.w3.org/2000/10/XMLSchema-instance"
                  xsi:schemaLocation="http://loiclacombe.com/emuconfig.xsd file:emuconfig.xsd">
  <SystemGroup Description="Consoles">
    <EmulatedSystem Description="Famicom">
      <CompatibleEmulator
        Name="nestopia"
        LibraryName="split_famicom" />
    </EmulatedSystem>
    <EmulatedSystem Description="Game Boy">
      <CompatibleEmulator
        Name="gambatte"
        LibraryName="split_gb" />
    </EmulatedSystem>
    <EmulatedSystem Description="Game Boy Color">
      <CompatibleEmulator
        Name="gambatte"
        LibraryName="split_gbc" />
    </EmulatedSystem>
    <EmulatedSystem Description="Game Boy Avance">
      <CompatibleEmulator
        Name="mednafen"
        LibraryName="split_gba" />
    </EmulatedSystem>
    <EmulatedSystem Description="Game Gear">
      <CompatibleEmulator
        Name="fusion"
        LibraryName="split_gamegear" />
    </EmulatedSystem>
    <EmulatedSystem Description="Master System">
      <CompatibleEmulator
        Name="fusion"
        LibraryName="split_mastersystem" />
    </EmulatedSystem>
    <EmulatedSystem Description="Megadrive">
      <CompatibleEmulator
        Name="fusion"
        LibraryName="split_megadrive" />
    </EmulatedSystem>
    <EmulatedSystem Description="Nintendo 64">
      <CompatibleEmulator
        Name="project64"
        LibraryName="split_nintendo64" />
    </EmulatedSystem>
    <EmulatedSystem Description="Super Famicom">
      <CompatibleEmulator
        Name="higan"
        LibraryName="higan_superfamicom" />
    </EmulatedSystem>
    <EmulatedSystem Description="Atari 2600">
      <CompatibleEmulator
        Name="stella"
        LibraryName="split_2600" />
    </EmulatedSystem>
    <EmulatedSystem Description="Playstation">
      <CompatibleEmulator
        Name="mednafen"
        LibraryName="split_psx" />
    </EmulatedSystem>

  </SystemGroup>

  <SystemGroup Description="Arcade" Enabled="false">
    <EmulatedSystem Description="Mame">
      <CompatibleEmulator
        Name="mame"
        LibraryName="mame"
        Enabled="false" />
    </EmulatedSystem>
  </SystemGroup>
  <Emulator Name="higan" Description="Higan">
    <EmulatorPathKey>emulators.higan.path</EmulatorPathKey>
    <CliParameters>"{0}" -fullscreen</CliParameters>
  </Emulator>
  <Emulator Name="fusion" Description="Fusion">
    <EmulatorPathKey>emulators.fusion.path</EmulatorPathKey>
    <CliParameters>"{0}" -fullscreen</CliParameters>
  </Emulator>
  <Emulator Name="nestopia" Description="NestopiaUE">
    <EmulatorPathKey>emulators.nestopia.path</EmulatorPathKey>
    <CliParameters>"{0}" -fullscreen</CliParameters>
  </Emulator>
  <Emulator Name="gambatte" Description="NestopiaUE">
    <EmulatorPathKey>emulators.gambatte.path</EmulatorPathKey>
    <CliParameters>"{0}" -fullscreen"</CliParameters>
  </Emulator>
  <Emulator Name="mednafen" Description="Mednafen">
    <EmulatorPathKey>emulators.mednafen.path</EmulatorPathKey>
    <CliParameters>"{0}"</CliParameters>
  </Emulator>
  <Emulator Name="project64" Description="Project 64">
    <EmulatorPathKey>emulators.project64.path</EmulatorPathKey>
    <CliParameters>"{0}" -fullscreen</CliParameters>
  </Emulator>
  <Emulator Name="mame" Description="Mame">
    <EmulatorPathKey>emulators.mame.path</EmulatorPathKey>
    <CliParameters>"{0}"</CliParameters>
  </Emulator>
  <Emulator Name="stella" Description="Stella">
    <EmulatorPathKey>emulators.stella.path</EmulatorPathKey>
    <CliParameters>"{0}"</CliParameters>
  </Emulator>

  <Library
    Name="split_famicom"
    LibraryClass="OtherParsers.SplitSet.Library"
    LibraryFolderKey="split.famicom.library" />
  <Library
    Name="split_gb"
    LibraryClass="OtherParsers.SplitSet.Library"
    LibraryFolderKey="split.gb.library" />
  <Library
    Name="split_gbc"
    LibraryClass="OtherParsers.SplitSet.Library"
    LibraryFolderKey="split.gbc.library" />
  <Library
    Name="split_gba"
    LibraryClass="OtherParsers.SplitSet.Library"
    LibraryFolderKey="split.gba.library" />
  <Library
    Name="split_gamegear"
    LibraryClass="OtherParsers.SplitSet.Library"
    LibraryFolderKey="split.gamegear.library" />
  <Library
    Name="split_mastersystem"
    LibraryClass="OtherParsers.SplitSet.Library"
    LibraryFolderKey="split.mastersystem.library" />
  <Library
    Name="split_megadrive"
    LibraryClass="OtherParsers.SplitSet.Library"
    LibraryFolderKey="split.megadrive.library" />
  <Library
    Name="split_nintendo64"
    LibraryClass="OtherParsers.SplitSet.Library"
    LibraryFolderKey="split.nintendo64.library" />
  <Library
    Name="split_psx"
    LibraryClass="OtherParsers.SplitSet.Library"
    LibraryFolderKey="split.psx.library">
      <RomExtension>cue</RomExtension>
      <RomExtension>ccd</RomExtension>
  </Library>

  <Library
    Name="split_2600"
    LibraryClass="OtherParsers.SplitSet.Library"
    LibraryFolderKey="split.2600.library">
    <RomExtension>zip</RomExtension>
    <RomExtension>bin</RomExtension>
  </Library>
  <Library
    Name="higan_superfamicom"
    LibraryClass="OtherParsers.Higan.Library"
    LibraryFolderKey="higan.superfamicom.library" />
  <Library
    Name="mame"
    LibraryClass="OtherParsers.Mame.Library"
    LibraryFolderKey="mame.all.library" />

</SystemConfigRoot>
